name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
      - 'v[0-9]+.[0-9]+.[0-9]+\+*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      image_name: ${{ steps.image_name.outputs.image_name }}
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=temp-
            type=raw,value=latest,enable=false
          labels: |
            org.opencontainers.image.title=${GITHUB_REPOSITORY#*/}
            org.opencontainers.image.version=${GITHUB_REF#refs/tags/v}
            org.opencontainers.image.created={{date 'YYYY-MM-DDTHH:mm:ssZ'}}
      - name: Split image name from tags
        id: image_name
        run: |
          image_name=$(echo ${{ steps.meta.outputs.tags }} | cut -d ':' -f 1)
          echo "image_name=${image_name}" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    strategy:
      matrix:
        platform:
          - name: amd64
            runner: ubuntu-24.04
          - name: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.platform.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/${{ matrix.platform.name }}
          provenance: true
          sbom: true
          tags: ${{ needs.prepare.outputs.image_name }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.platform.name }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    needs: [prepare, build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Create and push manifest
        run: |
          set -ex

          # Get all digest files
          digests=$(ls -1 ${{ runner.temp }}/digests/*)
          echo "Digests: $digests"

          # Create multi-platform manifest for each tag
          for tag in ${{ needs.prepare.outputs.tags }}; do
            echo "Creating manifest for $tag..."
            docker buildx imagetools create -t $tag \
              $(for digest in "${digests[@]}"; do echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${digest} "; done)
            
            echo "Verifying manifest..."
            docker buildx imagetools inspect $tag
          done
